Repository evvibrevi/ATJS_LAB_Juno_Project, pull requests merged in 2025-04, with the labels that each got.

#2 Added TypeScript configuration and deleted "test-examples" folder
  tests/demo-todo-app.spec.ts
  tsconfig.json
Labels: QUICKFIX, SPRINT 2

#7 13 - Install Sonar tools
  .github/workflows/playwright.yml
  .scannerwork/.sonar_lock
  .scannerwork/report-task.txt
  README.md
  package-lock.json
  package.json
  sonar-project.properties
Labels: SPRINT 2

#9 14 - Reportportal
  package-lock.json
  package.json
  playwright.config.ts
Labels: enhancement

#12 #21 - Added POM
  helpers/array-utils.ts
  pages/base.page.ts
  pages/cart.page.ts
  pages/components/common/base.component.ts
  pages/components/common/header/header.component.ts
  pages/components/common/header/searchBar.component.ts
  pages/components/common/productFilterSidebar.component.ts
  pages/components/common/productSortingFilter.component.ts
  pages/home.page.ts
  pages/popups/base.popup.ts
  pages/popups/cart.popup.ts
  pages/product.page.ts
  pages/productListing.page.ts
  pages/studioEquipment.page.ts
  playwright.config.ts
  tests/example.spec.ts
  tests/studioEquipmentPage/categoryPageLoadsSuccessfully.spec.t
  tests/studioEquipmentPage/productDetailsPageOpens.spec.t
  tests/studioEquipmentPage/searchFunctionalityWorks.spec.t
  tests/studioEquipmentPage/sortingByPrice.spec.t
  types/header.ts
Labels: SPRINT 3

#13 #21 - [QUICKFIX] added page folder to components
  pages/components/productLisitingPage/productFilterSidebar.component.ts
  pages/components/productLisitingPage/productSortingFilter.component.ts
  pages/productListing.page.ts
Labels: QUICKFIX, SPRINT 3

#15 [QUICKFIX] Fixes to POM, Sonar and delete extra code in pw config
  pages/components/common/header/header.component.ts
  pages/product.page.ts
  playwright.config.ts
  sonar-project.properties
  tests/demo-todo-app.spec.t
  tests/example.spec.ts
  tests/studioEquipmentPage/addToCart.spec.t
  tests/studioEquipmentPage/filterByBrand.spec.t
  tests/studioEquipmentPage/productPageLoaded.spec copy.t
Labels: QUICKFIX, SPRINT 3

#17 #22: Completed - Test suite with quality fixes and cookie/banner handling
  pages/base.page.ts
  pages/components/common/base.component.ts
  pages/components/common/footer.component.ts
  pages/components/common/header/header.component.ts
  pages/components/common/header/searchBar.component.ts
  pages/components/productLisitingPage/productFilterSidebar.component.ts
  pages/components/productLisitingPage/productSortingFilter.component.ts
  pages/popups/base.popup.ts
  pages/popups/cart.popup.ts
  pages/product.page.ts
  pages/productListing.page.ts
  playwright.config.ts
  sonar-project.properties
  state.json
  tests.zip
  tests/setup.t
  tests/studioEquipmentPage/breadcrumbNavigationWorks.spec.t
  tests/studioEquipmentPage/displayOfGoodsInCart.spec.t
  tests/studioEquipmentPage/filterByBrand.spec.t
  tests/studioEquipmentPage/navigationToHomepage.spec.t
  tests/studioEquipmentPage/searchFunctionalityWorks.spec.t
  tests/studioEquipmentPage/socialPagesLinksInteractions.spec.t
  tests/studioEquipmentPage/sortingByPrice.spec.t
Labels: SPRINT 3

#18 Juno overal
  pages/cart.page.ts
  pages/checkout.page.ts
  pages/components/checkout.component.ts
  pages/components/common/base.component.ts
  pages/components/common/header/header.component.ts
  pages/components/common/header/searchBar.component.ts
  pages/components/productLisitingPage/productFilterSidebar.component.ts
  pages/popups/cart.popup.ts
  pages/product.page.ts
  pages/productListing.page.ts
  tests/overalPage/addtoCart.spec.t
  tests/overalPage/checkout.spec.t
  tests/overalPage/filterFunctionality.spec.t
  tests/overalPage/homepageUIElements.spec.t
  tests/overalPage/localization.spec.t
  tests/overalPage/productPageDetails.spec.t
  tests/overalPage/searchFunctionality.spec.t
  types/header.ts
Labels: SPRINT 3

#19 #24 - Add API Tests with Axios and JSON Schema Validation
  apiSchemas/jsonSchemas.ts
  helpers/apiHelper.ts
  package-lock.json
  package.json
  tests/api/andrey/albums.spec.ts
  tests/api/andrey/comments.spec.ts
  tests/api/andrey/post.spec.ts
  tests/api/andrey/todos.spec.ts
  tests/api/andrey/users.spec.ts
  types/apiTypes.ts
Labels: SPRINT 4
